insert into icpc2013_team_regions (team_id, region_id, region_name, super_region_id, super_region_name) values ('1','1','The 2012 Arab Collegiate Programming Contest','1','Africa and the Middle East');
insert into icpc2013_team_regions (team_id, region_id, region_name, super_region_id, super_region_name) values ('2','2','The 2012 Northeastern Europe Regional Contest','2','Europe');
insert into icpc2013_team_regions (team_id, region_id, region_name, super_region_id, super_region_name) values ('3','3','The 2012 ACM-ICPC Asia Kanpur Regional Contest','3','Asia');
insert into icpc2013_team_regions (team_id, region_id, region_name, super_region_id, super_region_name) values ('4','1','The 2012 Arab Collegiate Programming Contest','1','Africa and the Middle East');
insert into icpc2013_team_regions (team_id, region_id, region_name, super_region_id, super_region_name) values ('5','4','The 2012 ACM-ICPC Asia Dhaka Regional Contest','3','Asia');
insert into icpc2013_team_regions (team_id, region_id, region_name, super_region_id, super_region_name) values ('6','5','The 2012 ACM-ICPC Asia Tianjin Regional Contest','3','Asia');
insert into icpc2013_team_regions (team_id, region_id, region_name, super_region_id, super_region_name) values ('7','6','The 2012 ACM-ICPC Asia Jinhua Regional Contest','3','Asia');
insert into icpc2013_team_regions (team_id, region_id, region_name, super_region_id, super_region_name) values ('8','7','The 2012 ACM-ICPC Asia Chengdu Regional Contest','3','Asia');
insert into icpc2013_team_regions (team_id, region_id, region_name, super_region_id, super_region_name) values ('9','2','The 2012 Northeastern Europe Regional Contest','2','Europe');
insert into icpc2013_team_regions (team_id, region_id, region_name, super_region_id, super_region_name) values ('10','1','The 2012 Arab Collegiate Programming Contest','1','Africa and the Middle East');
insert into icpc2013_team_regions (team_id, region_id, region_name, super_region_id, super_region_name) values ('11','8','The 2012 ACM-ICPC Asia Hanoi Regional Contest','3','Asia');
insert into icpc2013_team_regions (team_id, region_id, region_name, super_region_id, super_region_name) values ('12','9','The 2012 East Central NA Regional Contest','4','North America');
insert into icpc2013_team_regions (team_id, region_id, region_name, super_region_id, super_region_name) values ('13','10','The 2012 ACM-ICPC Asia Amritapuri Regional Contest','3','Asia');
insert into icpc2013_team_regions (team_id, region_id, region_name, super_region_id, super_region_name) values ('14','11','The 2012 Greater NY Regional Contest','4','North America');
insert into icpc2013_team_regions (team_id, region_id, region_name, super_region_id, super_region_name) values ('15','12','The 2012 Central Europe Regional Contest','2','Europe');
insert into icpc2013_team_regions (team_id, region_id, region_name, super_region_id, super_region_name) values ('16','13','The 2012 South America-North Regional Contest','5','Latin America');
insert into icpc2013_team_regions (team_id, region_id, region_name, super_region_id, super_region_name) values ('17','14','The 2012 Mexico & Central America Regional Contest','5','Latin America');
insert into icpc2013_team_regions (team_id, region_id, region_name, super_region_id, super_region_name) values ('18','15','The 2012 Southwestern Europe Regional Contest','2','Europe');
insert into icpc2013_team_regions (team_id, region_id, region_name, super_region_id, super_region_name) values ('19','16','The 2012 ACM-ICPC Asia Hangzhou Regional Contest','3','Asia');
insert into icpc2013_team_regions (team_id, region_id, region_name, super_region_id, super_region_name) values ('20','1','The 2012 Arab Collegiate Programming Contest','1','Africa and the Middle East');
insert into icpc2013_team_regions (team_id, region_id, region_name, super_region_id, super_region_name) values ('21','7','The 2012 ACM-ICPC Asia Chengdu Regional Contest','3','Asia');
insert into icpc2013_team_regions (team_id, region_id, region_name, super_region_id, super_region_name) values ('22','17','The 2012 ACM-ICPC Asia Hatyai Regional Contest','3','Asia');
insert into icpc2013_team_regions (team_id, region_id, region_name, super_region_id, super_region_name) values ('23','16','The 2012 ACM-ICPC Asia Hangzhou Regional Contest','3','Asia');
insert into icpc2013_team_regions (team_id, region_id, region_name, super_region_id, super_region_name) values ('24','10','The 2012 ACM-ICPC Asia Amritapuri Regional Contest','3','Asia');
insert into icpc2013_team_regions (team_id, region_id, region_name, super_region_id, super_region_name) values ('25','3','The 2012 ACM-ICPC Asia Kanpur Regional Contest','3','Asia');
insert into icpc2013_team_regions (team_id, region_id, region_name, super_region_id, super_region_name) values ('26','10','The 2012 ACM-ICPC Asia Amritapuri Regional Contest','3','Asia');
insert into icpc2013_team_regions (team_id, region_id, region_name, super_region_id, super_region_name) values ('27','18','The 2012 ACM-ICPC Asia Jakarta Regional Contest','3','Asia');
insert into icpc2013_team_regions (team_id, region_id, region_name, super_region_id, super_region_name) values ('28','19','The 2012 South America/Brazil Regional Contest','5','Latin America');
insert into icpc2013_team_regions (team_id, region_id, region_name, super_region_id, super_region_name) values ('29','20','The 2012 ACM-ICPC Asia Kharagpur Regional Contest','3','Asia');
insert into icpc2013_team_regions (team_id, region_id, region_name, super_region_id, super_region_name) values ('30','2','The 2012 Northeastern Europe Regional Contest','2','Europe');
insert into icpc2013_team_regions (team_id, region_id, region_name, super_region_id, super_region_name) values ('31','2','The 2012 Northeastern Europe Regional Contest','2','Europe');
insert into icpc2013_team_regions (team_id, region_id, region_name, super_region_id, super_region_name) values ('32','12','The 2012 Central Europe Regional Contest','2','Europe');
insert into icpc2013_team_regions (team_id, region_id, region_name, super_region_id, super_region_name) values ('33','21','The 2012 ACM-ICPC Asia Daejeon Regional Contest','3','Asia');
insert into icpc2013_team_regions (team_id, region_id, region_name, super_region_id, super_region_name) values ('34','2','The 2012 Northeastern Europe Regional Contest','2','Europe');
insert into icpc2013_team_regions (team_id, region_id, region_name, super_region_id, super_region_name) values ('35','2','The 2012 Northeastern Europe Regional Contest','2','Europe');
insert into icpc2013_team_regions (team_id, region_id, region_name, super_region_id, super_region_name) values ('36','22','The 2012 South Central USA Regional Contest','4','North America');
insert into icpc2013_team_regions (team_id, region_id, region_name, super_region_id, super_region_name) values ('37','23','The 2012 Northwestern Europe Regional Contest','2','Europe');
insert into icpc2013_team_regions (team_id, region_id, region_name, super_region_id, super_region_name) values ('38','24','The 2012 Northeast NA Regional Contest','4','North America');
insert into icpc2013_team_regions (team_id, region_id, region_name, super_region_id, super_region_name) values ('39','2','The 2012 Northeastern Europe Regional Contest','2','Europe');
insert into icpc2013_team_regions (team_id, region_id, region_name, super_region_id, super_region_name) values ('40','2','The 2012 Northeastern Europe Regional Contest','2','Europe');
insert into icpc2013_team_regions (team_id, region_id, region_name, super_region_id, super_region_name) values ('41','2','The 2012 Northeastern Europe Regional Contest','2','Europe');
insert into icpc2013_team_regions (team_id, region_id, region_name, super_region_id, super_region_name) values ('42','2','The 2012 Northeastern Europe Regional Contest','2','Europe');
insert into icpc2013_team_regions (team_id, region_id, region_name, super_region_id, super_region_name) values ('43','17','The 2012 ACM-ICPC Asia Hatyai Regional Contest','3','Asia');
insert into icpc2013_team_regions (team_id, region_id, region_name, super_region_id, super_region_name) values ('44','18','The 2012 ACM-ICPC Asia Jakarta Regional Contest','3','Asia');
insert into icpc2013_team_regions (team_id, region_id, region_name, super_region_id, super_region_name) values ('45','18','The 2012 ACM-ICPC Asia Jakarta Regional Contest','3','Asia');
insert into icpc2013_team_regions (team_id, region_id, region_name, super_region_id, super_region_name) values ('46','16','The 2012 ACM-ICPC Asia Hangzhou Regional Contest','3','Asia');
insert into icpc2013_team_regions (team_id, region_id, region_name, super_region_id, super_region_name) values ('47','6','The 2012 ACM-ICPC Asia Jinhua Regional Contest','3','Asia');
insert into icpc2013_team_regions (team_id, region_id, region_name, super_region_id, super_region_name) values ('48','2','The 2012 Northeastern Europe Regional Contest','2','Europe');
insert into icpc2013_team_regions (team_id, region_id, region_name, super_region_id, super_region_name) values ('49','25','The 2012 ACM-ICPC Asia Changchun Regional Contest','3','Asia');
insert into icpc2013_team_regions (team_id, region_id, region_name, super_region_id, super_region_name) values ('50','2','The 2012 Northeastern Europe Regional Contest','2','Europe');
insert into icpc2013_team_regions (team_id, region_id, region_name, super_region_id, super_region_name) values ('51','16','The 2012 ACM-ICPC Asia Hangzhou Regional Contest','3','Asia');
insert into icpc2013_team_regions (team_id, region_id, region_name, super_region_id, super_region_name) values ('52','26','The 2012 Mid-Central USA Regional Contest','4','North America');
insert into icpc2013_team_regions (team_id, region_id, region_name, super_region_id, super_region_name) values ('53','2','The 2012 Northeastern Europe Regional Contest','2','Europe');
insert into icpc2013_team_regions (team_id, region_id, region_name, super_region_id, super_region_name) values ('54','2','The 2012 Northeastern Europe Regional Contest','2','Europe');
insert into icpc2013_team_regions (team_id, region_id, region_name, super_region_id, super_region_name) values ('55','2','The 2012 Northeastern Europe Regional Contest','2','Europe');
insert into icpc2013_team_regions (team_id, region_id, region_name, super_region_id, super_region_name) values ('56','4','The 2012 ACM-ICPC Asia Dhaka Regional Contest','3','Asia');
insert into icpc2013_team_regions (team_id, region_id, region_name, super_region_id, super_region_name) values ('57','6','The 2012 ACM-ICPC Asia Jinhua Regional Contest','3','Asia');
insert into icpc2013_team_regions (team_id, region_id, region_name, super_region_id, super_region_name) values ('58','27','The 2012 ACM-ICPC Asia Tehran Regional Contest','3','Asia');
insert into icpc2013_team_regions (team_id, region_id, region_name, super_region_id, super_region_name) values ('59','25','The 2012 ACM-ICPC Asia Changchun Regional Contest','3','Asia');
insert into icpc2013_team_regions (team_id, region_id, region_name, super_region_id, super_region_name) values ('60','28','The 2012 North Central NA Regional Contest','4','North America');
insert into icpc2013_team_regions (team_id, region_id, region_name, super_region_id, super_region_name) values ('61','2','The 2012 Northeastern Europe Regional Contest','2','Europe');
insert into icpc2013_team_regions (team_id, region_id, region_name, super_region_id, super_region_name) values ('62','2','The 2012 Northeastern Europe Regional Contest','2','Europe');
insert into icpc2013_team_regions (team_id, region_id, region_name, super_region_id, super_region_name) values ('63','29','The 2012 Pacific Northwest Regional Contest','4','North America');
insert into icpc2013_team_regions (team_id, region_id, region_name, super_region_id, super_region_name) values ('64','21','The 2012 ACM-ICPC Asia Daejeon Regional Contest','3','Asia');
insert into icpc2013_team_regions (team_id, region_id, region_name, super_region_id, super_region_name) values ('65','30','The 2012 Southeastern Europe Regional Contest','2','Europe');
insert into icpc2013_team_regions (team_id, region_id, region_name, super_region_id, super_region_name) values ('66','1','The 2012 Arab Collegiate Programming Contest','1','Africa and the Middle East');
insert into icpc2013_team_regions (team_id, region_id, region_name, super_region_id, super_region_name) values ('67','16','The 2012 ACM-ICPC Asia Hangzhou Regional Contest','3','Asia');
insert into icpc2013_team_regions (team_id, region_id, region_name, super_region_id, super_region_name) values ('68','31','The 2012 ACM-ICPC Asia Tokyo Regional Contest','3','Asia');
insert into icpc2013_team_regions (team_id, region_id, region_name, super_region_id, super_region_name) values ('69','31','The 2012 ACM-ICPC Asia Tokyo Regional Contest','3','Asia');
insert into icpc2013_team_regions (team_id, region_id, region_name, super_region_id, super_region_name) values ('70','16','The 2012 ACM-ICPC Asia Hangzhou Regional Contest','3','Asia');
insert into icpc2013_team_regions (team_id, region_id, region_name, super_region_id, super_region_name) values ('71','1','The 2012 Arab Collegiate Programming Contest','1','Africa and the Middle East');
insert into icpc2013_team_regions (team_id, region_id, region_name, super_region_id, super_region_name) values ('72','32','The 2012 ACM-ICPC Asia Kaohsiung Regional Contest','3','Asia');
insert into icpc2013_team_regions (team_id, region_id, region_name, super_region_id, super_region_name) values ('73','5','The 2012 ACM-ICPC Asia Tianjin Regional Contest','3','Asia');
insert into icpc2013_team_regions (team_id, region_id, region_name, super_region_id, super_region_name) values ('74','2','The 2012 Northeastern Europe Regional Contest','2','Europe');
insert into icpc2013_team_regions (team_id, region_id, region_name, super_region_id, super_region_name) values ('75','33','The 2012 South America/South Regional Contest','5','Latin America');
insert into icpc2013_team_regions (team_id, region_id, region_name, super_region_id, super_region_name) values ('76','33','The 2012 South America/South Regional Contest','5','Latin America');
insert into icpc2013_team_regions (team_id, region_id, region_name, super_region_id, super_region_name) values ('77','34','The 2012 Caribbean Finals of the ACM-ICPC','5','Latin America');
insert into icpc2013_team_regions (team_id, region_id, region_name, super_region_id, super_region_name) values ('78','34','The 2012 Caribbean Finals of the ACM-ICPC','5','Latin America');
insert into icpc2013_team_regions (team_id, region_id, region_name, super_region_id, super_region_name) values ('79','13','The 2012 South America-North Regional Contest','5','Latin America');
insert into icpc2013_team_regions (team_id, region_id, region_name, super_region_id, super_region_name) values ('80','33','The 2012 South America/South Regional Contest','5','Latin America');
insert into icpc2013_team_regions (team_id, region_id, region_name, super_region_id, super_region_name) values ('81','33','The 2012 South America/South Regional Contest','5','Latin America');
insert into icpc2013_team_regions (team_id, region_id, region_name, super_region_id, super_region_name) values ('82','14','The 2012 Mexico & Central America Regional Contest','5','Latin America');
insert into icpc2013_team_regions (team_id, region_id, region_name, super_region_id, super_region_name) values ('83','13','The 2012 South America-North Regional Contest','5','Latin America');
insert into icpc2013_team_regions (team_id, region_id, region_name, super_region_id, super_region_name) values ('84','19','The 2012 South America/Brazil Regional Contest','5','Latin America');
insert into icpc2013_team_regions (team_id, region_id, region_name, super_region_id, super_region_name) values ('85','19','The 2012 South America/Brazil Regional Contest','5','Latin America');
insert into icpc2013_team_regions (team_id, region_id, region_name, super_region_id, super_region_name) values ('86','19','The 2012 South America/Brazil Regional Contest','5','Latin America');
insert into icpc2013_team_regions (team_id, region_id, region_name, super_region_id, super_region_name) values ('87','19','The 2012 South America/Brazil Regional Contest','5','Latin America');
insert into icpc2013_team_regions (team_id, region_id, region_name, super_region_id, super_region_name) values ('88','19','The 2012 South America/Brazil Regional Contest','5','Latin America');
insert into icpc2013_team_regions (team_id, region_id, region_name, super_region_id, super_region_name) values ('89','15','The 2012 Southwestern Europe Regional Contest','2','Europe');
insert into icpc2013_team_regions (team_id, region_id, region_name, super_region_id, super_region_name) values ('90','23','The 2012 Northwestern Europe Regional Contest','2','Europe');
insert into icpc2013_team_regions (team_id, region_id, region_name, super_region_id, super_region_name) values ('91','23','The 2012 Northwestern Europe Regional Contest','2','Europe');
insert into icpc2013_team_regions (team_id, region_id, region_name, super_region_id, super_region_name) values ('92','29','The 2012 Pacific Northwest Regional Contest','4','North America');
insert into icpc2013_team_regions (team_id, region_id, region_name, super_region_id, super_region_name) values ('93','30','The 2012 Southeastern Europe Regional Contest','2','Europe');
insert into icpc2013_team_regions (team_id, region_id, region_name, super_region_id, super_region_name) values ('94','35','The 2012 Rocky Mountain Regional Contest','4','North America');
insert into icpc2013_team_regions (team_id, region_id, region_name, super_region_id, super_region_name) values ('95','36','The 2012 South Africa Regional Contest','1','Africa and the Middle East');
insert into icpc2013_team_regions (team_id, region_id, region_name, super_region_id, super_region_name) values ('96','37','The 2012 Southeast USA Regional Contest','4','North America');
insert into icpc2013_team_regions (team_id, region_id, region_name, super_region_id, super_region_name) values ('97','26','The 2012 Mid-Central USA Regional Contest','4','North America');
insert into icpc2013_team_regions (team_id, region_id, region_name, super_region_id, super_region_name) values ('98','24','The 2012 Northeast NA Regional Contest','4','North America');
insert into icpc2013_team_regions (team_id, region_id, region_name, super_region_id, super_region_name) values ('99','7','The 2012 ACM-ICPC Asia Chengdu Regional Contest','3','Asia');
insert into icpc2013_team_regions (team_id, region_id, region_name, super_region_id, super_region_name) values ('100','37','The 2012 Southeast USA Regional Contest','4','North America');
insert into icpc2013_team_regions (team_id, region_id, region_name, super_region_id, super_region_name) values ('101','8','The 2012 ACM-ICPC Asia Hanoi Regional Contest','3','Asia');
insert into icpc2013_team_regions (team_id, region_id, region_name, super_region_id, super_region_name) values ('102','26','The 2012 Mid-Central USA Regional Contest','4','North America');
insert into icpc2013_team_regions (team_id, region_id, region_name, super_region_id, super_region_name) values ('103','35','The 2012 Rocky Mountain Regional Contest','4','North America');
insert into icpc2013_team_regions (team_id, region_id, region_name, super_region_id, super_region_name) values ('104','28','The 2012 North Central NA Regional Contest','4','North America');
insert into icpc2013_team_regions (team_id, region_id, region_name, super_region_id, super_region_name) values ('105','38','The 2012 Mid-Atlantic USA Regional Contest','4','North America');
insert into icpc2013_team_regions (team_id, region_id, region_name, super_region_id, super_region_name) values ('106','28','The 2012 North Central NA Regional Contest','4','North America');
insert into icpc2013_team_regions (team_id, region_id, region_name, super_region_id, super_region_name) values ('107','39','The 2012 South Pacific Programming Contest','6','South Pacific');
insert into icpc2013_team_regions (team_id, region_id, region_name, super_region_id, super_region_name) values ('108','40','The 2012 Southern California Regional Contest','4','North America');
insert into icpc2013_team_regions (team_id, region_id, region_name, super_region_id, super_region_name) values ('109','39','The 2012 South Pacific Programming Contest','6','South Pacific');
insert into icpc2013_team_regions (team_id, region_id, region_name, super_region_id, super_region_name) values ('110','27','The 2012 ACM-ICPC Asia Tehran Regional Contest','3','Asia');
insert into icpc2013_team_regions (team_id, region_id, region_name, super_region_id, super_region_name) values ('111','9','The 2012 East Central NA Regional Contest','4','North America');
insert into icpc2013_team_regions (team_id, region_id, region_name, super_region_id, super_region_name) values ('112','38','The 2012 Mid-Atlantic USA Regional Contest','4','North America');
insert into icpc2013_team_regions (team_id, region_id, region_name, super_region_id, super_region_name) values ('113','12','The 2012 Central Europe Regional Contest','2','Europe');
insert into icpc2013_team_regions (team_id, region_id, region_name, super_region_id, super_region_name) values ('114','9','The 2012 East Central NA Regional Contest','4','North America');
insert into icpc2013_team_regions (team_id, region_id, region_name, super_region_id, super_region_name) values ('115','28','The 2012 North Central NA Regional Contest','4','North America');
insert into icpc2013_team_regions (team_id, region_id, region_name, super_region_id, super_region_name) values ('116','12','The 2012 Central Europe Regional Contest','2','Europe');
insert into icpc2013_team_regions (team_id, region_id, region_name, super_region_id, super_region_name) values ('117','2','The 2012 Northeastern Europe Regional Contest','2','Europe');
insert into icpc2013_team_regions (team_id, region_id, region_name, super_region_id, super_region_name) values ('118','30','The 2012 Southeastern Europe Regional Contest','2','Europe');
insert into icpc2013_team_regions (team_id, region_id, region_name, super_region_id, super_region_name) values ('119','7','The 2012 ACM-ICPC Asia Chengdu Regional Contest','3','Asia');
insert into icpc2013_team_regions (team_id, region_id, region_name, super_region_id, super_region_name) values ('120','25','The 2012 ACM-ICPC Asia Changchun Regional Contest','3','Asia');
