#!/bin/bash
# This script can be used to perform multiple tasks specifically
# on ICPC-live image instances. It must be run as root.

set -e

error()
{
	echo "Error: $@"
	exit 1
}

[ `id -u` -eq 0 ] || error "this program must be run as root."

case "$1" in
	rootpass)
		echo "Updating system root password..."
		passwd

		echo "Updating MySQL root password..."
		read -es -p "Enter new MySQL password: "  PASS1 ; echo
		read -es -p "Retype new MySQL password: " PASS2 ; echo
		[ "x$PASS1" = "x$PASS2" ] || error "passwords do not match."
		# Use Debian administrative credentials to login to the MySQL server.
		/usr/bin/mysql --defaults-file=/etc/mysql/debian.cnf mysql <<EOF
UPDATE user SET password=PASSWORD('$PASS1') WHERE user='root';
FLUSH PRIVILEGES;
EOF
		echo "MySQL root password updated."

		rm /etc/issue
		ln -s /etc/issue.djlive /etc/issue
		;;

	upgrade)
		apt-get update
		apt-get dist-upgrade -y
		apt-get clean
		;;

	initcontest)
		[ -z "$2" ] && error "no contest specified"
		if [ `echo "$2" | sed 's/[^a-zA-Z0-9]//'` != "$2" ]; then
			error "contest identifier contains illegal characters"
		fi
		CONTESTID=$2

		cat ~icpclive/autoanalyst/create_icat_instance.sql | \
			sed "s/icpc2013/$CONTESTID/g" | \
			/usr/bin/mysql --defaults-file=/etc/mysql/debian.cnf icat

		;;

     *|help)
     cat <<EOF
Usage: $0 <command> [argument]...

Commands:
  rootpass     (re)set system and MySQL database root passwords
  upgrade      install system (security) updates
  initcontest  initialize for a new contest, pass contest identifier
                 string as argument (alphanumeric characters only)
  help         display this usage information

EOF
	 exit 0
	 ;;

esac
